// Generated by CoffeeScript 1.6.3
(function() {
  var njs_util,
    __slice = [].slice;

  njs_util = require('nodejs-util');

  this.dir = function(message, x) {
    var key, keys, _i, _len;
    log('');
    log('----------------------------------');
    log(message);
    log('');
    keys = ((function() {
      var _results;
      _results = [];
      for (key in x) {
        _results.push(key);
      }
      return _results;
    })()).sort();
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      log('*', key);
    }
    return null;
  };

  this.log = function() {
    var P, p;
    P = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return GLOBAL.print(((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = P.length; _i < _len; _i++) {
        p = P[_i];
        _results.push(TYPES.isa_text(p) ? p : rpr(p));
      }
      return _results;
    })()).join(' '));
  };

  this.rpr = function(x) {
    var error, type;
    try {
      return njs_util.inspect(x, rpr.options);
    } catch (_error) {
      error = _error;
      type = TYPES.type_of(x);
      return "unable to serialize object of type " + type + "; message: " + (rpr(error['message']));
    }
  };

  this.rpr.options = {
    showHidden: false,
    depth: 4,
    colors: true,
    customInspect: false
  };

  this.xray = function(x) {
    return njs_util.inspect(x, this.xray.options);
  };

  this.xray.options = {
    showHidden: true,
    depth: 42,
    colors: true,
    customInspect: false
  };

}).call(this);
