// Generated by CoffeeScript 1.6.3
(function() {
  var join;

  join = function(prefix, suffix) {

    /* Poor Man's `path.join`—not recommended for serious use. */
    if (/^\/$/.test(suffix)) {
      return suffix;
    }
    return (prefix.replace(/\/$/, '')).concat('/', suffix);
  };

  this.require = function(route) {
    var R, error, idx, line, source, _i, _len, _ref;
    if (this.require.prefix == null) {
      throw new Error("must set `require.prefix` to route before using `require()`");
    }
    route = join(this.require.prefix, route);
    if (!/\js$/.test(route)) {
      route = route + '.js';
    }
    if ((R = this.require.cache[route]) != null) {
      return R;
    }
    source = GLOBAL.readFile(route);
    source = this.require.head.concat(source, this.require.tail);
    try {
      R = eval(source);
    } catch (_error) {
      error = _error;

      /* TAINT need better error handling */
      _ref = source.split('\n');
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        line = _ref[idx];
        GLOBAL.print(idx + 1, '  ', line);
      }
      GLOBAL.print();
      GLOBAL.print("an error occurred when trying to evaluate " + route + ":");
      GLOBAL.print(error['message']);
      GLOBAL.print(error['stack']);
      GLOBAL.print();
    }
    this.require.cache[route] = R;
    return R;
  };

  this.require.head = "(function() {\nvar exports = {};\nvar module  = { 'exports': exports };\n(function() {\n\n";

  this.require.tail = "\n}).call( module.exports );\nreturn module.exports;\n})();";

  this.require.cache = {};

  this.require.prefix = void 0;

}).call(this);
